-- MySQL Script generated by MySQL Workbench
-- Wed Oct 20 00:02:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taskforce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taskforce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taskforce` DEFAULT CHARACTER SET utf8;
USE `taskforce`;

-- -----------------------------------------------------
-- Table `taskforce`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`categories`
(
    `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`       VARCHAR(30)  NOT NULL,
    `alias` VARCHAR(20)  NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`chats`
(
    `id`          INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `created_at`  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `task_id`     INT UNSIGNED     NOT NULL,
    `sender_id`   INT UNSIGNED     NOT NULL,
    `receiver_id` INT UNSIGNED     NOT NULL,
    `message`     TEXT             NOT NULL,
    `is_read`     TINYINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    CONSTRAINT `chats_senders_fk`
        FOREIGN KEY (`sender_id`)
            REFERENCES `taskforce`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `chats_tasks_fk`
        FOREIGN KEY (`task_id`)
            REFERENCES `taskforce`.`tasks` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `chats_receivers_fk`
        FOREIGN KEY (`receiver_id`)
            REFERENCES `taskforce`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `chats_senders_fk_idx` ON `taskforce`.`chats` (`sender_id` ASC) VISIBLE;

CREATE INDEX `chats_tasks_fk_idx` ON `taskforce`.`chats` (`task_id` ASC) VISIBLE;

CREATE INDEX `chats_receivers_fk_idx` ON `taskforce`.`chats` (`receiver_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `taskforce`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`cities`
(
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`        VARCHAR(30)  NOT NULL,
    `coordinates` POINT        NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`favourites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`favourites`
(
    `id`           INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `owner_id`     INT UNSIGNED NOT NULL,
    `favourite_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `favourites_owners_fk`
        FOREIGN KEY (`owner_id`)
            REFERENCES `taskforce`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `favourites_chosen_fk`
        FOREIGN KEY (`favourite_id`)
            REFERENCES `taskforce`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `favourites_owners_fk_idx` ON `taskforce`.`favourites` (`owner_id` ASC) VISIBLE;

CREATE INDEX `favourites_chosen_fk_idx` ON `taskforce`.`favourites` (`favourite_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `taskforce`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`files`
(
    `id`   INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `path` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskforce`.`files_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`files_tasks`
(
    `id`      INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `task_id` INT UNSIGNED NOT NULL,
    `file_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `files_tasks_fk`
        FOREIGN KEY (`task_id`)
            REFERENCES `taskforce`.`tasks` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `files_ids_fk`
        FOREIGN KEY (`file_id`)
            REFERENCES `taskforce`.`files` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `files_tasks_fk_idx` ON `taskforce`.`files_tasks` (`task_id` ASC) VISIBLE;

CREATE INDEX `files_ids_fk_idx` ON `taskforce`.`files_tasks` (`file_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `taskforce`.`files_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`files_users`
(
    `id`      INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` INT UNSIGNED NOT NULL,
    `file_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `files_users_fk`
        FOREIGN KEY (`user_id`)
            REFERENCES `taskforce`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `files_id_fk`
        FOREIGN KEY (`file_id`)
            REFERENCES `taskforce`.`files` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `files_users_fk_idx` ON `taskforce`.`files_users` (`user_id` ASC) VISIBLE;

CREATE INDEX `files_ids_fk_idx` ON `taskforce`.`files_users` (`file_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `taskforce`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`notifications`
(
    `id`         INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `created_at` TIMESTAMP        NULL     DEFAULT CURRENT_TIMESTAMP,
    `user_id`    INT UNSIGNED     NOT NULL,
    `type`       VARCHAR(10)      NOT NULL,
    `is_new`     TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `task_id`    INT UNSIGNED     NOT NULL,
    `review_id`  INT UNSIGNED     NULL,
    `chat_id`    INT UNSIGNED     NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `notifications_users_fk`
        FOREIGN KEY (`user_id`)
            REFERENCES `taskforce`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `notifications_tasks_fk`
        FOREIGN KEY (`task_id`)
            REFERENCES `taskforce`.`tasks` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `notifications_reviews_fk`
        FOREIGN KEY (`review_id`)
            REFERENCES `taskforce`.`reviews` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `notifications_chats_fk`
        FOREIGN KEY (`chat_id`)
            REFERENCES `taskforce`.`chats` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `notifications_chats_fk_idx` ON `taskforce`.`notifications` (`chat_id` ASC) VISIBLE;

CREATE INDEX `notifications_tasks_fk_idx` ON `taskforce`.`notifications` (`task_id` ASC) VISIBLE;

CREATE INDEX `notifications_users_fk_idx` ON `taskforce`.`notifications` (`user_id` ASC) VISIBLE;

CREATE INDEX `notifications_reviews_fk_idx` ON `taskforce`.`notifications` (`review_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `taskforce`.`responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`responses`
(
    `id`          INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `created_at`  TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `status`      TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `task_id`     INT UNSIGNED     NOT NULL,
    `executor_id` INT UNSIGNED     NOT NULL,
    `price`       INT UNSIGNED     NULL     DEFAULT NULL,
    `message`     TEXT             NULL     DEFAULT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `responses_tasks_fk`
        FOREIGN KEY (`task_id`)
            REFERENCES `taskforce`.`tasks` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `responses_users_fk`
        FOREIGN KEY (`executor_id`)
            REFERENCES `taskforce`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `responses_tasks_idx` ON `taskforce`.`responses` (`task_id` ASC) VISIBLE;

CREATE INDEX `responses_users_idx` ON `taskforce`.`responses` (`executor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `taskforce`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`reviews`
(
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `created_at`  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `task_id`     INT UNSIGNED NOT NULL,
    `executor_id` INT UNSIGNED NOT NULL,
    `customer_id` INT UNSIGNED NOT NULL,
    `description` TEXT         NULL     DEFAULT NULL,
    `rating`      INT          NULL     DEFAULT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `reviews_tasks_fk`
        FOREIGN KEY (`task_id`)
            REFERENCES `taskforce`.`tasks` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `reviews_executors_fk`
        FOREIGN KEY (`executor_id`)
            REFERENCES `taskforce`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `reviews_customers_fk`
        FOREIGN KEY (`customer_id`)
            REFERENCES `taskforce`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `reviews_tasks_idx` ON `taskforce`.`reviews` (`task_id` ASC) VISIBLE;

CREATE INDEX `reviews_executors_idx` ON `taskforce`.`reviews` (`executor_id` ASC) VISIBLE;

CREATE INDEX `reviews_customers_idx` ON `taskforce`.`reviews` (`customer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `taskforce`.`users_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`users_categories`
(
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id`     INT UNSIGNED NOT NULL,
    `category_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `users_categories_fk`
        FOREIGN KEY (`user_id`)
            REFERENCES `taskforce`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `users_categories_fk`
        FOREIGN KEY (`category_id`)
            REFERENCES `taskforce`.`categories` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `users_categories_fk_idx` ON `taskforce`.`users_categories` (`user_id` ASC) VISIBLE;

CREATE INDEX `users_categories_idx` ON `taskforce`.`users_categories` (`category_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `taskforce`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`tasks`
(
    `id`            INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `created_at`    TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `customer_id`   INT UNSIGNED     NOT NULL,
    `executor_id`   INT UNSIGNED     NULL     DEFAULT NULL,
    `status`        TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `title`         VARCHAR(30)      NOT NULL,
    `description`   TEXT             NOT NULL,
    `category_id`   INT UNSIGNED     NOT NULL,
    `city_id`       INT UNSIGNED     NULL     DEFAULT NULL,
    `location_info` TEXT             NULL     DEFAULT NULL,
    `address`       VARCHAR(50)      NULL     DEFAULT NULL,
    `budget`        INT UNSIGNED     NULL     DEFAULT NULL,
    `deadline`      DATE             NULL     DEFAULT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `tasks_executors_fk`
        FOREIGN KEY (`executor_id`)
            REFERENCES `taskforce`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `tasks_customers_fk`
        FOREIGN KEY (`customer_id`)
            REFERENCES `taskforce`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `tasks_categories_fk`
        FOREIGN KEY (`category_id`)
            REFERENCES `taskforce`.`categories` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `tasks_cities_fk`
        FOREIGN KEY (`city_id`)
            REFERENCES `taskforce`.`cities` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `tasks_executors_idx` ON `taskforce`.`tasks` (`executor_id` ASC) VISIBLE;

CREATE INDEX `tasks_customers_idx` ON `taskforce`.`tasks` (`customer_id` ASC) VISIBLE;

CREATE INDEX `tasks_categories_fk_idx` ON `taskforce`.`tasks` (`category_id` ASC) VISIBLE;

CREATE INDEX `tasks_cities_fk_idx` ON `taskforce`.`tasks` (`city_id` ASC) VISIBLE;

CREATE FULLTEXT INDEX `task_title_FULLTEXT` ON `taskforce`.`tasks` (`title`) VISIBLE;


-- -----------------------------------------------------
-- Table `taskforce`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskforce`.`users`
(
    `id`                    INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `created_at`            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `name`                  VARCHAR(20)  NOT NULL,
    `email`                 VARCHAR(40)  NOT NULL,
    `password`              VARCHAR(255) NOT NULL,
    `city_id`               INT UNSIGNED NOT NULL,
    `birthday`              DATE         NULL     DEFAULT NULL,
    `avatar_id`             INT UNSIGNED NULL     DEFAULT NULL,
    `about`                 TEXT         NULL     DEFAULT NULL,
    `role`                  VARCHAR(15)  NOT NULL DEFAULT 'employer',
    `last_seen`             TIMESTAMP    NULL     DEFAULT NULL,
    `phone`                 VARCHAR(12)  NULL     DEFAULT NULL,
    `skype`                 VARCHAR(20)  NULL     DEFAULT NULL,
    `telegram`              VARCHAR(20)  NULL     DEFAULT NULL,
    `notify_new_message`    TINYINT      NULL     DEFAULT 1,
    `notify_task_action`    TINYINT      NULL     DEFAULT 1,
    `notify_new_review`     TINYINT      NULL     DEFAULT 1,
    `setting_hide_contacts` TINYINT      NULL     DEFAULT 0,
    `setting_hide_profile`  TINYINT      NULL     DEFAULT 0,
    PRIMARY KEY (`id`),
    CONSTRAINT `users_cities_fk`
        FOREIGN KEY (`city_id`)
            REFERENCES `taskforce`.`cities` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `users_files_fk`
        FOREIGN KEY (`avatar_id`)
            REFERENCES `taskforce`.`files` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `taskforce`.`users` (`email` ASC) VISIBLE;

CREATE FULLTEXT INDEX `user_name_FULLTEXT` ON `taskforce`.`users` (`name`) VISIBLE;

CREATE INDEX `users_cities_fk_idx` ON `taskforce`.`users` (`city_id` ASC) VISIBLE;

CREATE INDEX `users_files_fk_idx` ON `taskforce`.`users` (`avatar_id` ASC) VISIBLE;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
